"""Shared helpers for the Parcel Pilot procedural asset pipeline.

Every model in the game is generated by a script in blender/assets/ that
builds geometry with these helpers. Nothing is hand-modeled and no .blend
file is the source of truth.
"""
